-- Seed catalog: the 20 products from the original products.js

INSERT INTO products (id, slug, name, category, description, price, original_price, rating, review_count, image_url, alt_text, badge_text, badge_class, stock, active, cultural, festival, version, created_at, updated_at) VALUES
(1, 'luxury-hamper-box', 'Luxury Hamper Box', 'gift sets', 'A beautifully curated hamper packed with premium goodies — perfect for any celebration.', 499.00, 699.00, 4.9, 182, 'https://t4.ftcdn.net/jpg/05/32/64/27/240_F_532642742_3lStpC5P0U4FrndE82prkwm61F5OnQgj.jpg', 'Luxury gift hamper box with curated items', 'Bestseller', 'pbadge--bestseller', 50, TRUE, FALSE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(2, 'engraved-timepiece', 'Engraved Timepiece', 'accessories', 'A timeless watch with custom engraving — the gift that tells time and stories.', 1299.00, 1699.00, 4.8, 94, 'https://etchcraftemporium.in/cdn/shop/files/ChatGPT_Image_Aug_14_2025_07_16_41_PM.png?v=1755179225&width=800', 'Elegant engraved timepiece watch gift', 'New', 'pbadge--new', 50, TRUE, FALSE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(3, 'classic-rose-bouquet', 'Classic Rose Bouquet', 'flowers', 'Fresh red roses arranged by expert florists — delivered same day in Mumbai.', 599.00, 799.00, 4.6, 310, 'https://www.uflowershop.com/1294-large_default/valentine-s-day-classic-red-rose-bouquet.webp', 'Classic red rose bouquet for gifting', 'Sale', 'pbadge--sale', 50, TRUE, FALSE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(4, 'signature-perfume', 'Signature Perfume', 'fragrance', 'A sophisticated fragrance crafted to leave a lasting impression — luxury in a bottle.', 1199.00, 1499.00, 4.9, 218, 'https://images.stockcake.com/public/e/b/3/eb3d9618-4d24-4f60-bf9c-17168329eb84_large/elegant-perfume-bottle-stockcake.jpg', 'Elegant signature perfume bottle gift', 'Top Rated', 'pbadge--rated', 50, TRUE, FALSE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(5, 'personalised-memory-journal', 'Personalised Memory Journal', 'personalized', 'A custom-name embossed leather journal — perfect for the thinker, writer, or dreamer.', 349.00, 499.00, 4.7, 143, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYHMpPD82BbPD-XU5Sy5FkvJ18kjiHDYcGeAvo_ebW_Q&s=10', 'Open leather journal for writing', 'Sale', 'pbadge--sale', 50, TRUE, FALSE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(6, 'artisan-chocolate-box', 'Artisan Chocolate Box', 'food & sweets', 'Handcrafted Belgian chocolates in an elegant box — a crowd-pleasing delight for all ages.', 299.00, 399.00, 4.8, 276, 'https://www.fnp.com/images/pr/x/v20240619124652/artisan-chocolate-medley_1.jpg', 'Assorted artisan chocolate gift box', 'Bestseller', 'pbadge--bestseller', 50, TRUE, FALSE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(7, 'pashmina-shawl', 'Pashmina Shawl', 'accessories', 'A buttery-soft pure pashmina shawl — a timeless, elegant gift for the women in your life.', 899.00, 1199.00, 4.7, 88, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYVNFC5xSccFz_ABiLHmqALbxu8wtUT3JaE_badgJZZq0AOYVwcBse63QH&s=10', 'Soft folded pashmina shawl in warm tones', 'Sale', 'pbadge--sale', 50, TRUE, FALSE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(8, 'succulent-plant-gift-set', 'Succulent Plant Gift Set', 'home decor', 'A charming set of low-maintenance succulents — a living, growing reminder of your care.', 449.00, 599.00, 4.5, 192, 'https://nurserylive.com/cdn/shop/products/nurserylive-bulk-gifts-splendid-succulents-gift-pack-16969345368204.jpg?v=1634229204&width=800', 'Small succulent plants in decorative pots', 'New', 'pbadge--new', 50, TRUE, FALSE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(9, 'customised-star-map-print', 'Customised Star Map Print', 'personalized', 'A framed print of the night sky on your most special date — a deeply personal, one-of-a-kind gift.', 799.00, 999.00, 4.9, 127, 'http://www.nookatyou.com/cdn/shop/files/9_be3ba05c-077c-47f0-bc13-dba884092b05.png?v=1758794209', 'Night sky star map art print', 'Top Rated', 'pbadge--rated', 50, TRUE, FALSE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(10, 'luxury-spa-gift-set', 'Luxury Spa Gift Set', 'wellness', 'Bath salts, essential oils, and face masks in an elegant box — the ultimate self-care collection.', 1099.00, 1499.00, 4.8, 201, 'https://m.media-amazon.com/images/I/61goHt3M-rL._AC_UF1000,1000_QL80_.jpg', 'Spa products flatlay with bath oils and flowers', 'Bestseller', 'pbadge--bestseller', 50, TRUE, FALSE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(11, 'wireless-earbuds-premium', 'Wireless Earbuds Premium', 'accessories', 'Crystal-clear sound, active noise cancellation — a gift for the music lover and the focused worker.', 1999.00, 2499.00, 4.7, 156, 'https://www.leafstudios.in/cdn/shop/files/1_5e005039-83c1-4054-ba73-cda7f78fb128_800x.png?v=1786005631', 'White wireless earbuds in charging case', 'New', 'pbadge--new', 50, TRUE, FALSE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(12, 'handmade-warli-art-frame', 'Handmade Warli Art Frame', 'cultural', 'Authentic hand-painted Warli art from Maharashtra tribal artists — culture, heritage, and beauty in one frame.', 649.00, 899.00, 4.8, 73, 'https://umedmart.com/cdn/shop/files/UM-BC-WPWF-06.jpg?v=1753864866&width=1200', 'Colourful handmade art painting on canvas', 'Bestseller', 'pbadge--bestseller', 50, TRUE, TRUE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(13, 'diwali-premium-sweets-box', 'Diwali Premium Sweets Box', 'food & sweets', 'A royal box of premium mithai, dry fruits, and handmade chocolates — the perfect Diwali gift.', 799.00, 999.00, 4.9, 341, 'https://www.fnp.com/images/pr/l/v20250924141021/diwali-premium-sweetness-box_1.jpg', 'Traditional Indian mithai sweets in box', 'Bestseller', 'pbadge--bestseller', 50, TRUE, FALSE, TRUE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(14, 'rakhi-special-gift-combo', 'Rakhi Special Gift Combo', 'gift sets', 'A thoughtfully curated Rakhi combo with chocolates, dry fruits, and a personalised card for your brother.', 499.00, 699.00, 4.7, 189, 'https://m.media-amazon.com/images/I/71zJoiEofWL._AC_UF894,1000_QL80_.jpg', 'Colourful thread bracelet gift for sibling', 'Sale', 'pbadge--sale', 50, TRUE, FALSE, TRUE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(15, 'leather-wallet-and-card-holder', 'Leather Wallet & Card Holder', 'accessories', 'Full-grain leather wallet with RFID protection and matching card holder — practical luxury for everyday life.', 749.00, 999.00, 4.6, 112, 'https://www.starelabs.com/wp-content/uploads/2023/10/Vegan-Leather-Card-And-Cash-Holder-2-2-600x400.jpg', 'Brown leather bifold wallet open on surface', 'Sale', 'pbadge--sale', 50, TRUE, FALSE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(16, 'paithani-silk-bookmark-set', 'Paithani Silk Bookmark Set', 'cultural', 'Handwoven Paithani silk bookmarks in traditional Maharashtra patterns — a cultural treasure in miniature.', 399.00, 549.00, 4.6, 47, 'http://froggmag.com/cdn/shop/files/FDBM2B6-1-1.png?v=1689835808', 'Books with decorative silk bookmark', 'New', 'pbadge--new', 50, TRUE, TRUE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(17, 'scented-candle-gift-set', 'Scented Candle Gift Set', 'wellness', 'Three hand-poured soy wax candles in signature scents — for evenings that deserve to feel special.', 549.00, 749.00, 4.7, 168, 'https://houseofaroma.in/wp-content/uploads/2023/02/scented-candle-gift-set-combo-pack-4.webp', 'Three lit scented candles glowing warmly', 'Sale', 'pbadge--sale', 50, TRUE, FALSE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(18, 'graduation-memory-box', 'Graduation Memory Box', 'personalized', 'A personalised keepsake box with photo frame and memory slots — celebrate their achievement in style.', 899.00, 1199.00, 4.8, 91, 'https://m.media-amazon.com/images/I/81v1jwVtBRL._AC_UF350,350_QL80_.jpg', 'Graduation cap and diploma certificate', 'Top Rated', 'pbadge--rated', 50, TRUE, FALSE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(19, 'kolhapuri-craft-jewellery-box', 'Kolhapuri Craft Jewellery Box', 'cultural', 'A hand-carved Kolhapuri leather jewellery box — exquisite craftsmanship from Maharashtra''s artisans.', 849.00, 1099.00, 4.8, 62, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdZTE8mUeso3MUIngRXQbzHKlMeTHaWjA4uGi0fC5kQQ&s=10', 'Open jewellery box with compartments', 'Bestseller', 'pbadge--bestseller', 50, TRUE, TRUE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6)),
(20, 'couple-photo-book', 'Couple Photo Book', 'personalized', 'A custom hardcover photo book filled with your shared memories — a gift that tells your story.', 699.00, 899.00, 4.9, 203, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMVe5ghu_yzrPAaGPNdJpXo0ej72Q839A1bBNH7c5ofA&s=10', 'Open photo album with memories', 'Top Rated', 'pbadge--rated', 50, TRUE, FALSE, FALSE, 0, UTC_TIMESTAMP(6), UTC_TIMESTAMP(6));

INSERT INTO product_tags (product_id, tag) VALUES
(1, 'for-her'),
(1, 'for-him'),
(1, 'premium'),
(2, 'for-him'),
(2, 'premium'),
(2, 'personalized'),
(3, 'for-her'),
(3, 'budget'),
(4, 'for-her'),
(4, 'for-him'),
(4, 'premium'),
(5, 'for-her'),
(5, 'for-him'),
(5, 'personalized'),
(5, 'budget'),
(6, 'for-her'),
(6, 'for-him'),
(6, 'budget'),
(7, 'for-her'),
(7, 'premium'),
(8, 'for-her'),
(8, 'for-him'),
(8, 'budget'),
(9, 'for-her'),
(9, 'for-him'),
(9, 'personalized'),
(9, 'premium'),
(10, 'for-her'),
(10, 'premium'),
(11, 'for-him'),
(11, 'for-her'),
(11, 'premium'),
(12, 'for-her'),
(12, 'for-him'),
(12, 'personalized'),
(13, 'for-her'),
(13, 'for-him'),
(13, 'premium'),
(14, 'for-him'),
(14, 'budget'),
(15, 'for-him'),
(15, 'premium'),
(16, 'for-her'),
(16, 'budget'),
(16, 'personalized'),
(17, 'for-her'),
(17, 'premium'),
(17, 'budget'),
(18, 'for-her'),
(18, 'for-him'),
(18, 'personalized'),
(18, 'premium'),
(19, 'for-her'),
(19, 'premium'),
(19, 'personalized'),
(20, 'for-her'),
(20, 'for-him'),
(20, 'personalized'),
(20, 'premium');

INSERT INTO product_occasions (product_id, occasion) VALUES
(1, 'birthday'),
(1, 'anniversary'),
(1, 'festival'),
(2, 'birthday'),
(2, 'anniversary'),
(2, 'graduation'),
(3, 'valentine'),
(3, 'anniversary'),
(3, 'birthday'),
(4, 'birthday'),
(4, 'valentine'),
(4, 'anniversary'),
(5, 'birthday'),
(5, 'graduation'),
(5, 'anniversary'),
(6, 'birthday'),
(6, 'valentine'),
(6, 'festival'),
(7, 'birthday'),
(7, 'anniversary'),
(7, 'festival'),
(8, 'birthday'),
(8, 'graduation'),
(8, 'anniversary'),
(9, 'anniversary'),
(9, 'valentine'),
(9, 'birthday'),
(10, 'birthday'),
(10, 'anniversary'),
(10, 'valentine'),
(11, 'birthday'),
(11, 'graduation'),
(11, 'anniversary'),
(12, 'birthday'),
(12, 'anniversary'),
(12, 'festival'),
(13, 'festival'),
(14, 'festival'),
(14, 'birthday'),
(15, 'birthday'),
(15, 'graduation'),
(15, 'anniversary'),
(16, 'birthday'),
(16, 'graduation'),
(16, 'festival'),
(17, 'birthday'),
(17, 'anniversary'),
(17, 'valentine'),
(18, 'graduation'),
(18, 'birthday'),
(19, 'birthday'),
(19, 'anniversary'),
(19, 'festival'),
(20, 'anniversary'),
(20, 'valentine'),
(20, 'birthday');

INSERT INTO product_for_whom (product_id, for_whom) VALUES
(1, 'her'),
(1, 'him'),
(2, 'him'),
(3, 'her'),
(4, 'her'),
(4, 'him'),
(5, 'her'),
(5, 'him'),
(6, 'her'),
(6, 'him'),
(7, 'her'),
(8, 'her'),
(8, 'him'),
(9, 'her'),
(9, 'him'),
(10, 'her'),
(11, 'him'),
(11, 'her'),
(12, 'her'),
(12, 'him'),
(13, 'her'),
(13, 'him'),
(14, 'him'),
(15, 'him'),
(16, 'her'),
(17, 'her'),
(18, 'her'),
(18, 'him'),
(19, 'her'),
(20, 'her'),
(20, 'him');

INSERT INTO product_personalities (product_id, personality) VALUES
(1, 'expressive'),
(1, 'extrovert'),
(2, 'minimalist'),
(2, 'practical'),
(3, 'expressive'),
(3, 'extrovert'),
(4, 'expressive'),
(4, 'minimalist'),
(5, 'introvert'),
(5, 'creative'),
(5, 'minimalist'),
(6, 'extrovert'),
(6, 'expressive'),
(6, 'practical'),
(7, 'minimalist'),
(7, 'practical'),
(7, 'introvert'),
(8, 'introvert'),
(8, 'creative'),
(8, 'minimalist'),
(9, 'creative'),
(9, 'expressive'),
(9, 'introvert'),
(10, 'introvert'),
(10, 'minimalist'),
(10, 'expressive'),
(11, 'practical'),
(11, 'extrovert'),
(11, 'minimalist'),
(12, 'creative'),
(12, 'introvert'),
(12, 'expressive'),
(13, 'extrovert'),
(13, 'expressive'),
(13, 'practical'),
(14, 'practical'),
(14, 'extrovert'),
(15, 'minimalist'),
(15, 'practical'),
(16, 'introvert'),
(16, 'creative'),
(16, 'minimalist'),
(17, 'introvert'),
(17, 'minimalist'),
(17, 'expressive'),
(18, 'expressive'),
(18, 'creative'),
(18, 'extrovert'),
(19, 'expressive'),
(19, 'creative'),
(19, 'extrovert'),
(20, 'expressive'),
(20, 'creative'),
(20, 'extrovert');

INSERT INTO product_relationships (product_id, relationship) VALUES
(1, 'partner'),
(1, 'parent'),
(1, 'friend'),
(2, 'partner'),
(2, 'parent'),
(2, 'sibling'),
(3, 'partner'),
(3, 'friend'),
(4, 'partner'),
(4, 'friend'),
(4, 'sibling'),
(5, 'friend'),
(5, 'sibling'),
(5, 'partner'),
(6, 'friend'),
(6, 'colleague'),
(6, 'sibling'),
(6, 'parent'),
(7, 'mother'),
(7, 'parent'),
(7, 'partner'),
(7, 'sibling'),
(8, 'friend'),
(8, 'colleague'),
(8, 'sibling'),
(9, 'partner'),
(9, 'friend'),
(10, 'partner'),
(10, 'friend'),
(10, 'sibling'),
(10, 'parent'),
(11, 'sibling'),
(11, 'friend'),
(11, 'partner'),
(12, 'parent'),
(12, 'friend'),
(12, 'partner'),
(13, 'parent'),
(13, 'colleague'),
(13, 'friend'),
(13, 'partner'),
(14, 'sibling'),
(15, 'partner'),
(15, 'friend'),
(15, 'sibling'),
(15, 'parent'),
(16, 'friend'),
(16, 'sibling'),
(16, 'colleague'),
(17, 'friend'),
(17, 'partner'),
(17, 'sibling'),
(18, 'friend'),
(18, 'sibling'),
(18, 'partner'),
(19, 'partner'),
(19, 'parent'),
(19, 'friend'),
(20, 'partner');

ALTER TABLE products AUTO_INCREMENT = 100;

INSERT INTO coupons (code, type, discount_value, min_order_amount, max_discount, usage_limit, used_count, active) VALUES
('GIFT20', 'PERCENT', 20.00, 0.00, 1000.00, NULL, 0, TRUE),
('WELCOME', 'FLAT', 100.00, 299.00, NULL, NULL, 0, TRUE);
